services:

  # Local Installation Doc 👇
  # https://airflow.apache.org/docs/apache-airflow/stable/start.html
  # Docker Image Doc 👇 
  # https://airflow.apache.org/docs/docker-stack/index.html
  
  # https://hub.docker.com/r/apache/airflow
  # Airflow Home: /opt/airflow/
  airflow:
    image: airflow-dev
    build: .
    container_name: airflow
    ports:
      - 8080:8080
    environment:
      DATALAKE_HOST: "/data"
    volumes:
      - ./airflow/dags/:/opt/airflow/dags
      - ./airflow/scripts/:/opt/airflow/scripts/
      - ./data:/data
